DROP TABLE EMPLOYEE;

CREATE TABLE EMPLOYEE (
  ID NUMBER(10,0) NOT NULL AUTO_INCREMENT,
  FIRSTNAME VARCHAR(255) NOT NULL DEFAULT '',
  LASTNAME VARCHAR(255) NOT NULL DEFAULT '',
  TITLE VARCHAR(255) NOT NULL DEFAULT '',
  PHONENUMBER VARCHAR(255) NOT NULL DEFAULT '',
  EMAIL VARCHAR(255) NOT NULL DEFAULT '',
  HIREDATE VARCHAR(255) NOT NULL DEFAULT '',
  MANAGER VARCHAR(255) NOT NULL DEFAULT '',
  DEPARTMENT VARCHAR(255) NOT NULL DEFAULT '',
  PRIMARY KEY (ID));

DROP TABLE DEPARTMENT;

CREATE TABLE DEPARTMENT (
  ID NUMBER(10,0) NOT NULL AUTO_INCREMENT,
  DEPTNUM VARCHAR (6) NOT NULL DEFAULT '',
  DEPTNAME VARCHAR(255) not null default '',
  MANAGER VARCHAR(255) NOT NULL DEFAULT '',
  PRIMARY KEY (ID)
);

DROP SEQUENCE hibernate_sequence;

CREATE SEQUENCE hibernate_sequence;