CREATE TABLE EMPLOYEE (
  ID INT NOT NULL AUTO_INCREMENT,
  FIRST_NAME VARCHAR(50) DEFAULT NULL,
  LAST_NAME VARCHAR(50) DEFAULT NULL,
  TITLE VARCHAR(50) DEFAULT NULL,
  PHONE_NUMBER VARCHAR(12) DEFAULT NULL,
  EMAIL VARCHAR(255) DEFAULT NULL,
  HIRE_DATE VARCHAR(20) DEFAULT NULL,
  MANAGER_ID INT DEFAULT NULL,
  DEPT_NUM INT DEFAULT NULL,
  PRIMARY KEY (ID));

CREATE TABLE DEPARTMENT (
  ID NUMBER(10,0) NOT NULL AUTO_INCREMENT,
  DEPT_NUM INT DEFAULT NULL,
  DEPT_NAME VARCHAR(50) DEFAULT NULL,
  MANAGER_ID INT DEFAULT NULL,
  PRIMARY KEY (ID));

DROP SEQUENCE hibernate_sequence;

CREATE SEQUENCE hibernate_sequence;